baseURL = "https://ooni.org"
languageCode = "en-us"
title = "OONI: Open Observatory of Network Interference"
DefaultContentLanguage = "en"
pluralizeListTitles = false

[params]
description = "The Open Observatory of Network Interference (OONI) is a global community measuring internet censorship around the world. Run OONI Probe to detect internet censorship. Use OONI Explorer to track internet censorship worldwide in near real-time."
probeDesktopVersion = "3.0.0"

[Languages]
[Languages.ar]
[Languages.en]
[Languages.es]
[Languages.ca]
[Languages.fr]
[Languages.pt]
[Languages.zh]

[outputFormats]
[outputFormats.PageIndex]
mediaType = "application/json"
baseName = "pageindex"
isPlainText = true
notAlternative = true

[outputs]
  home = ["HTML", "PageIndex", "RSS"]
